version: 0.0

os: linux 

files:
  - source: /
    destination: /app
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: root

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
      - location: scripts/after_install.sh
        timeout: 3000
        runas: root

  ApplicationStart:
    - location: scripts/start_server.sh     
      timeout: 300
      runas: root